[package]
name = "wally"
version = "0.1.0"
authors = ["Siddharth Yadav <siddharth_yadav@outlook.com>"]
edition = "2018"

[dependencies]
config = "0.9.2"
json = "0.11.13"
reqwest = "0.9.8"
clap = "2.32.0"
urlencoding = "1.0.0"